### ISSUE TITLE
Please add support for python 3.10

### ISSUE THREAD

**Issue by KamarajuKusumanchi** [wireservice/agate#769]
The setup.py currently shows
```
...
        'Programming Language :: Python :: 3.7',
        'Programming Language :: Python :: 3.8',
        'Programming Language :: Python :: 3.9',
...
```
Could you please add support for Python 3.10 as well? It is the latest stable version as per https://www.python.org/downloads/ and was released on 2021-10-04.

**Comment by demiurg** [comment]
We are on python 3.11 now, and I'm getting `ImportError: cannot import name 'Sequence' from 'collections'`

**Comment by jpmckinney** [comment]
If you install from GitHub, it works on Python 3.10 and 3.11.

Note that it already worked on Python 3.10 - we just hadn't updated the classifiers on PyPI.

I'll make a release when I can.

**Comment by KamarajuKusumanchi** [comment]
> If you install from GitHub, it works on Python 3.10 and 3.11.

You may be right. But in my case, I do not install agate directly. Instead, it gets pulled in as a transitive dependency when I install some other packages via conda. If the support for 3.10 and 3.11 is not explicitly mentioned, conda will not install the package.

If you could make the release with explicit support for 3.10 and 3.11, it will be very useful.

**Comment by jpmckinney** [comment]
New version has been released.
